name: Deploy on Push, Commit, or Merge to Master

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - closed

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        run: |
          git config --global user.name "Karina"
          git config --global user.email "thealisky@gmail.com"

      # 1. Checkout репозитория
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Установите зависимости
      - name: Install dependencies
        run: |
          npm install

      # 3. Постройте проект
      - name: Build project
        run: |
          npm run build
      # 4. Деплой проекта
      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm run deploy

