name: Test Coverage

on:
  pull_request:
    branches:
      - master
      - main
      - develop
      - G3.3-unit-test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm test